syntax = "proto3";
package events.v1;

import "google/type/money.proto";
// import "google/protobuf/empty.proto";
import "google/type/timeofday.proto";
import "google/type/date.proto";

// EventResponse — структура для передачи информации о мероприятии
message Event {
   // Format — формат проведения события (онлайн, оффлайн и т.д.)
  message Format {
    string name = 1;
    string description = 2;
  }

  // EventType — тип события (Конференция, Воркшоп, платное, Митап)
  message EventType {
    string name = 1;
    string description = 2;
  }

  // Event — основная информация о событии
  string name = 1;
  string description = 2;
  google.type.Date date_start = 3;
  google.type.Date date_end = 4;
  google.type.TimeOfDay time_start = 5;
  google.type.TimeOfDay time_end = 6;
  google.type.Money price = 7;
  string source_url = 8;
  string organizer_name = 9;
  string region_name = 10;
  string category_name = 11;

  Format format = 12;
  EventType event_type = 13;
}

// ListEvents - массив event 
message ListEvents {
  repeated Event events = 1;
}

// EventsService — сервис для работы с мероприятиями
service Events {
  // ListEvents — возвращает поток событий
  rpc SendListEvents(ListEvents) returns (ListEvents);
  rpc StreamEvents(ListEvents) returns (stream Event);
}
